---
apiVersion: v1
kind: Pod
metadata:
  name: rbac
  labels:
    app: rbac
spec:
  serviceAccountName: default
  containers:
  - name: rbac
    image: mohamadmokhtar/library:kubectl-v1.23.15
    imagePullPolicy: IfNotPresent
    stdin: true
    tty: true
  terminationGracePeriodSeconds: 5
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
 - kind: ServiceAccount
   name: default
   namespace: default