apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  strategy:
    type: RollingUpdate
  minReadySeconds: 15
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: mohamadmokhtar/library:go-http-server-v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
        env:
         - name: SERVER_PORT
           value: "80"
        readinessProbe:
          httpGet:
            port: 80
            path: /healthz
          initialDelaySeconds: 2
          periodSeconds: 1
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: zone
                operator: In
                values:
                 - east