---
apiVersion: v1
kind: Pod
metadata:
  name: rbac
  labels:
    app: rbac
spec:
  serviceAccountName: default
  containers:
  - name: rbac
    image: mohamadmokhtar/library:kubectl-v1.23.15
    imagePullPolicy: IfNotPresent
    stdin: true
    tty: true
  terminationGracePeriodSeconds: 5
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-access
rules:
- apiGroups:
  - ""
  verbs:
  - "*"
  resources:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-access-bind
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-access
subjects:
 - kind: ServiceAccount
   name: default
   namespace: default