apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    app: server
spec:
  ports:
  - port: 80
    name: http
  clusterIP: None
  selector:
    app: server
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: server
spec:
  selector:
    matchLabels:
      app: server 
  replicas: 1
  template:
    metadata:
      labels:
        app: server 
    spec:
      containers:
      - name: server
        image: mohamadmokhtar/library:post-http-server-v1
        imagePullPolicy: IfNotPresent
        env:
        - name: SERVER_PORT
          value: "80"
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "nfs"
      resources:
        requests:
          storage: 1Gi