apiVersion: v1
kind: Service
metadata:
  name: server
spec:
  type: NodePort
  selector:
    app: server
    ver: v1
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      nodePort: 30080