apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monitor
  labels:
    app: monitor
spec:
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
      - name: monitor
        image: mohamadmokhtar/library:monitor
        imagePullPolicy: IfNotPresent
      # changed from first example
      nodeSelector:
        kubernetes.io/hostname: node1