apiVersion: batch/v1
kind: Job
metadata:
  name: counter-comlete
  labels:
    app: counter
spec:
  completions: 5
  template:
    metadata:
      labels:
        app: counter
    spec:
    restartPolicy: OnFailure
      containers:
      - name: counter
        image: mohamadmokhtar/library:count