apiVersion: batch/v1
kind: CronJob
metadata:
  name: every-five-min-job
spec:
  schdule: "*/5 * * * *"
  jobTemplate:
    completions: 5
    parallelism: 2
    template:
    metadata:
      labels:
      app: counter
    spec:
      restartPolicy: OnFailure # optional default is Always, available options Always, Never, OnFailure
      containers:
      - name: counter
        image: mohamadmokhtar/library:count