##### ENV Example ####
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sleep
  labels:
    app: sleep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
    spec:
      containers:
      - name: sleep
        image: mohamadmokhtar/library:sleep
        imagePullPolicy: IfNotPresent
        env:
         - name: SLEEP_TIME
           value: "100"