##### Not Ready pod ##########
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  publishNotReadyAddresses: true
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80